# Generated by Django 5.1.7 on 2025-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('course', 'Course Only'), ('private', 'Private')], max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
