# Generated by Django 5.1.7 on 2025-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_token', models.CharField(max_length=50, unique=True)),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('course_end_date', models.DateField(blank=True, null=True)),
                ('enrollment_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
    ]
