# Generated by Django 4.2.20 on 2025-04-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_answer', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/%d/')),
                ('submission_status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Late', 'Late')], max_length=50)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('review_status', models.CharField(choices=[('Graded', 'Graded'), ('Not Graded', 'Not Graded')], default='Not Graded', max_length=50)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
            ],
            options={
                'db_table': 'Assignment_Submissions',
            },
        ),
    ]
