# Generated by Django 5.1.7 on 2025-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submission_status', models.CharField(max_length=50)),
                ('review_status', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'AssignmentSubmissions',
            },
        ),
    ]
